CREATE TABLE blogful_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password TEXT NOT NULL,
  nickname TEXT,
  date_created TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  date_modified TIMESTAMP WITH TIME ZONE
);

ALTER TABLE blogful_articles
  ADD COLUMN
    author_id INTEGER REFERENCES blogful_users(id)
    ON DELETE SET NULL;
